CFLAGS  = -Wall -g -pthread
FUENTE1 = sync-a.c
#FUENTE2 = sync-b.c
PROG1   = SyncA
#PROG2   = SyncB

all :
	gcc $(CFLAGS) -o $(PROG1) $(FUENTE1)
#	gcc $(CFLAGS) -o $(PROG2) $(FUENTE2)

clean :
	-rm $(PROG)
